### ISSUE TITLE
搜索按钮的bug

### ISSUE THREAD

**Issue by guo-weijie** [blueedgetechno/windows11#12]
**Describe the bug**
打开搜索框，此时点击其他区域（除搜索按钮和搜索框外的其他任意区域）时，搜索框会显示为开始菜单，然后关闭

translated: Open the search box, when you click on other areas (any area except the search button and search box), the search box will be displayed as the start menu, and then closed.

**Desktop (please complete the following information):**
 - OS: windows 10 21H1
 - Browser edge、chrome、firefox
 - Version 最新版（截止目前，即2021年7月23日09点29分）

**Comment by blueedgetechno** [comment]
Cann you translate your question in English?

**Comment by blueedgetechno** [comment]
Ok, I get the question but Its not a bug, I mean it is maybe ... but ... Okay I will fix it but its not a breaking one.

**Comment by guo-weijie** [comment]
yes,i will




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blueedgetechno/windows11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月23日(星期五) 中午1:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [blueedgetechno/windows11] 搜索按钮的bug (#12)





 
Cann you translate your question in English?
