### ISSUE TITLE
windows11 Component

### ISSUE THREAD

**Issue by TrumanDu** [blueedgetechno/windows11#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Whether to consider developing a series of component libraries to support Windows 11 UI?
**Describe alternatives you've considered**

**Additional context**

**Comment by blueedgetechno** [comment]
I know there are few good UI out there but they might not be exactly what you need. Also I discovered the UI after creating the custom UI from scratch.

It really depends whether you want a comprehensive way to develop the UI or you can also get around without following any proper component flow.
