### ISSUE TITLE
Update Favicon.ico

### ISSUE THREAD

**Issue by C47F15H** [blueedgetechno/windows11#16]
**Describe the bug**
Wrong logo/favicon.ico of Windows 11

**To Reproduce**
![](https://raw.githubusercontent.com/blueedgetechno/windows11/master/public/favicon.ico)
this is what is used here
<img src="https://user-images.githubusercontent.com/80169337/126862046-43048242-be03-46f6-811d-52945786d571.png" height="64">
and this is the one used.

**Comment by blueedgetechno** [comment]
Both are official logo's of windows 11. The one that you purposed is the solid color logo. Why do you think the first one is wrong or should be updated?

**Comment by C47F15H** [comment]
Both **may** be official but the one used here looks like the logo of Windows 10X with a flat design
And the second one is the one used almost everywhere

Links:
https://logos.fandom.com/wiki/Microsoft_Windows
https://www.theverge.com/2021/5/18/22442421

Now I'm making a pull request

**Comment by blueedgetechno** [comment]
Again if its official, we don't have to changed anything whether or not it looks like windows 10x logo

**Comment by C47F15H** [comment]
ok
