### ISSUE TITLE
night light

### ISSUE THREAD

**Issue by 5alidshammout** [blueedgetechno/windows11#22]
I think when you activate the night light button, there should be a filter that converts white to yellow (blue light filter)
here is an image I found on google about that:

![Image](https://apkmagic.com.ar/wp-content/uploads/2019/04/Night-Light-Pro-Blue-Light-Filter-Night-Mode-v1.19.4.24-paid-Paid-APK.png)

**Comment by blueedgetechno** [comment]
I know, they are just placeholders. Not everything works at this point but eventually will with the course of time.

**Comment by blueedgetechno** [comment]
Its done
