### ISSUE TITLE
Make responsible for mobile phones 

### ISSUE THREAD

**Issue by DLRAM** [blueedgetechno/windows11#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DLRAM** [comment]
Yes

**Comment by blueedgetechno** [comment]
I will be responsible about this issue.

**Comment by CyberDevv** [comment]
I was thinking it shouldn't be available on mobile phones since it is an OS based on desktops, so if visited on mobile phones, a pages should show up that it can only be viewed on desktops

**Comment by blueedgetechno** [comment]
@CyberDevv Exactly, I had a idea about posting a joke when opened in mobile, "Even Microsoft couldn't make it far with windows on phone then how could I?"

**Comment by Lukas-Batema** [comment]
> @CyberDevv Exactly, I had a idea about posting a joke when opened in mobile, "Even Microsoft couldn't make it far with windows on phone then how could I?"

That is great! I would love to see this ;)

**Comment by CyberDevv** [comment]
> @CyberDevv Exactly, I had a idea about posting a joke when opened in mobile, "Even Microsoft couldn't make it far with windows on phone then how could I?"

Yeah, that will make sense also

**Comment by Lukas-Batema** [comment]
When will this be added? It still loads on my iPhone in Firefox... I would use the booting screen, and replace the losing spinner, with just non-animated text (in the correct font, obviously), that says the error you want to.

**Comment by blueedgetechno** [comment]
@Lukas-Batema I added this in previous update but for the development I disabled it and forgot to enable in production.

Will do asap

**Comment by blueedgetechno** [comment]
done
