### ISSUE TITLE
Calendar does not hide completely when choose a month which has 6 rows

### ISSUE THREAD

**Issue by WalterBrightHub** [blueedgetechno/windows11#34]
**Describe the bug**
in the right bottom calendar, it will not hide completely if we choose a month which has 6 rows.

**To Reproduce**
1. Select a month which has 6 rows, for example, October 2021
2. Close the calendar

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22427576/127194492-537b12ff-917d-42e4-bef7-08c5ab20f481.png)

![微信图片_20210728003815](https://user-images.githubusercontent.com/22427576/127193840-279f5894-8267-4738-99bd-c30f09f9c3b8.png)

**Desktop:**
 - OS: Windows
 - Browser :Chrome
 - Version :92.0.4515.107

**Comment by blueedgetechno** [comment]
That's weird coz I cannot reproduce the error. Still I will lower the bottom property of calender even more, just in case.
