### ISSUE TITLE
Right click menu doesn't work when right clicking in right side

### ISSUE THREAD

**Issue by Tronic247** [blueedgetechno/windows11#40]
# Right click menu doesn't work when right clicking in right side
## Right side
![image](https://user-images.githubusercontent.com/76736580/127672757-6e32704a-def0-4e1f-ae7f-3fa10e8e03ec.png)
## left Side
![image](https://user-images.githubusercontent.com/76736580/127672770-26bd3de9-1ce4-4cb9-91d5-d1b26a12cc38.png)

**Comment by blueedgetechno** [comment]
It will be fixed it the next patch

**Comment by Tronic247** [comment]
OK
