### ISSUE TITLE
Change "Action Center"

### ISSUE THREAD

**Issue by peasoft** [blueedgetechno/windows11#47]
Windows 11 moves the "Action Center" to Calendar bar, but the site is still using the old style. Can you change it?

**Comment by blueedgetechno** [comment]
I will, I used the first insider release which has it.

**Comment by Rajaniraiyn** [comment]
@blueedgetechno I have created the new windows 11 action center within my [windows11](https://github.com/Rajaniraiyn/windows11) project. but it is vanilla JS. and added that you can use Microsoft's official [Fluent UI react components](https://developer.microsoft.com/en-us/fluentui#/controls/web) as well.

**Comment by Tronic247** [comment]
> 
> 
> @blueedgetechno I have created the new windows 11 action center within my [windows11](https://github.com/Rajaniraiyn/windows11) project. but it is vanilla JS. and added that you can use Microsoft's official [Fluent UI react components](https://developer.microsoft.com/en-us/fluentui#/controls/web) as well.


your win11 is not the same !!

**Comment by Rajaniraiyn** [comment]
yes that's because we haven't see a live windows 11

**Comment by Tronic247** [comment]
> 
> 
> yes that's because we haven't seen a live windows 11


Very sad. me too

**Comment by Tronic247** [comment]
> 
> 
> @Tronic247 yes that's because we haven't seen a live windows 11.
> This is the one of the repo that resembles the actual one more.
> I just give you a template. I guess @blueedgetechno has actual windows 11 so you guys can improve and use yourselves.


from my knowledge you should change the font "Arial" to "Segoe UI"

**Comment by Rajaniraiyn** [comment]
> > @Tronic247 yes that's because we haven't seen a live windows 11.
> > This is the one of the repo that resembles the actual one more.
> > I just give you a template. I guess @blueedgetechno has actual windows 11 so you guys can improve and use yourselves.
> 
> from my knowledge you should change the font "Arial" to "Segoe UI"

I know Microsoft is using new `Segoe UI Variable` font for windows 11. I am unable to get one.
I am using default `sans serif` not `Arial`

**Comment by Rajaniraiyn** [comment]
Finally I got that font and Icons. please refer #65

**Comment by Tronic247** [comment]
https://aka.ms/SegoeUIVariable

**Comment by Tronic247** [comment]
https://github.com/blueedgetechno/windows11/discussions/50

**Comment by Rajaniraiyn** [comment]
There are many variants check static-text and static-display.

**Comment by blueedgetechno** [comment]
Reconsidering font selection of Segoe UI variable, thanks to @Tronic247

**Comment by Rajaniraiyn** [comment]
@blueedgetechno still if the variable font causes issue then try using [`font-optical-sizing`](https://css-tricks.com/almanac/properties/f/font-optical-sizing/#this-only-works-on-fonts-that-support-optical-sizing) or [`font-variation-settings`](https://css-tricks.com/almanac/properties/f/font-optical-sizing/#another-way-to-optically-size-fonts)

**Comment by blueedgetechno** [comment]
done
