### ISSUE TITLE
it shows win version as 10

### ISSUE THREAD

**Issue by Ccode-lang** [blueedgetechno/windows11#7]

**Comment by blueedgetechno** [comment]
Can you elaborate?

**Comment by Arciiix** [comment]
@blueedgetechno I guess he meant the build version, which is 10.0.22000.51 (and it's a correct Windows 11 Insider Preview version). To find it, open the Terminal and type "ver".  You'll get "Microsoft Windows [Version 10.0.22000.51]".

@Ccode-lang is this what you mean?

**Comment by blueedgetechno** [comment]
@Arciiix I know right! I used those version numbers from insider preview just to be real.
