### ISSUE TITLE
Booting animation and User login screen

### ISSUE THREAD

**Issue by nikhiltadikonda** [blueedgetechno/windows11#78]
Two things:

* Is it possible to include a windows 11 boot screen/animation when the website is opened?

For reference:
![Windows-11-new-boot-animation](https://user-images.githubusercontent.com/40952012/131078247-1e9b11cd-0de2-440b-a66c-4e39ddd9cb53.png)

If possible, include any sound of your choice when the boot animation is running

* Including a User login screen with a dummy password?

For reference:
![images](https://user-images.githubusercontent.com/40952012/131078886-b06d17d0-4263-4388-8334-2b09da590450.jpeg)

**Comment by blueedgetechno** [comment]
done
