### ISSUE TITLE
Minimal Design And User friendly experience

### ISSUE THREAD

**Issue by Bhushan1010** [blueedgetechno/windows11#86]
It will be helpful for new beginner who took interest in computer field and it will give experience.

Wallpapers should be 3d animated and silent and calm to get mantal stability and looks great on pc/laptop.

**Comment by Bhushan1010** [comment]
Just a feedback

**Comment by blueedgetechno** [comment]
duly noted

**Comment by blueedgetechno** [comment]
About 3d animated wallpapers, It is already buffering for various reasons for low wnd pc, introducing memory intensive video files will make it more difficult. The only alternative so far is gif files but they are low quality and produce jarring frame rates.

I will love to hear another solution.

**Comment by Bhushan1010** [comment]
Oh sorry. I didn't consider the low end pc/laptop but, As you said its right.

Thanks for replying.
