### ISSUE TITLE
Logon User Interface

### ISSUE THREAD

**Issue by TheTechWin** [blueedgetechno/windows11#92]
Hi Guys! It is me. Yatin,
Hope you know me, I am on your Discord server.

I am requesting you guys to make a logon UI.
So, I will be making a reference to it.

And I request @blueedgetechno please take a look at it.
@blueedgetechno Also, try translating the HTML code to React.

**Comment by TheTechWin** [comment]
The start menu is pretty weird. The user logged in is only you @blueedgetechno.
So you can change it to like "Guest"

I am just giving you a suggestion. Do not take it very seriously if you do not want to do this.

**Comment by blueedgetechno** [comment]
The boot screen and login screen is under development

**Comment by TheTechWin** [comment]
> The boot screen and login screen is under development

Ok. But do not close this issue, we are still developing it right?
