### ISSUE TITLE
Decrease the size of the windows logo in the booting screen

### ISSUE THREAD

**Issue by Tronic247** [blueedgetechno/windows11#95]

**Comment by blueedgetechno** [comment]
why

**Comment by blueedgetechno** [comment]
I took the reference from here #78

**Comment by Tronic247** [comment]
I mean decrease the size ! It's too big 
![image](https://user-images.githubusercontent.com/76736580/131484734-f3b517b3-2f2a-4889-9eb0-a75a5e8a9719.png)
Vs
![image](https://user-images.githubusercontent.com/76736580/131484765-b6349459-f505-4603-9a03-ee9cd29e418e.png)

**Comment by blueedgetechno** [comment]
I dont think its required, It will be even good for bigger screen.
