### ISSUE TITLE
Command Line Bug

### ISSUE THREAD

**Issue by TheTechWin** [blueedgetechno/windows11#98]
When you hit Enter with a blank space in Command Prompt,
You get this :
 
'' is not recognized as an internal or external command,
operable program or batch file.

Please fix this.

![image](https://user-images.githubusercontent.com/88525903/131438237-bef42fcf-b36f-474d-a360-925a2a063a88.png)

**Comment by blueedgetechno** [comment]
okay, will be fixed in next push
